- name: configure payment component
  hosts: payment
  become: yes
  tasks:
  - name: install python3 and pip 
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: installed
      loop:
      - python3
      - gcc
      - python3-deval
  - name: create app directory
    ansible.builtin.file:
    path: /app
    state: directory
  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app
  - name: download payment code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v2.zip 
      dest: /tmp/payment.zip

  - name: extract code
    ansible.builtin.unarchieve

    src: /tmp/payment.zip
    dest: /app
    remote_src: yes
  - name: install dependencies:
    ansinle.builtin.pip:
    requirement: requirement.txt
    executable: pip3.9
    args: 
       chdir: /app
  - name: copy payment service
    ansible.builtin.copy:
     src: payment.service
     dest: /etc/systemd/system/payment.service
  - name: daemon-reload
    ansible.builtin.systemd:
    daemon-reload: true
  - name: start and enable service
    ansible.builtin.service:
      name: payment
      state: started
      enabled: yes

  
  